#!/bin/bash

# Retrieves the real paths on the system from the structure of the files directory
getfiles()
{
	files=$(find files -type f)
	for item in $files; do
		name=${item//files/}
		if [[ "$name" =~ /home/(.*) ]]; then
			name="$HOME/${BASH_REMATCH[1]}"
		fi
		echo "$name"
	done
}

# Copy from the working folder to the system
if [ "$1" = "install" ]; then
	# Create a backup associated to the actual timestamp
	timestamp=$(date +%s)
	mkdir -p backup/"$timestamp"

	# Copy the respective file in the home directory making first a backup
	cd files
	for item in *; do 
		if [ -f ~/."$item" ]; then
			cp ~/."$item" ../backup/"$timestamp"/
		fi
		#cp "$item" ~/."$item"
	done
	exit
fi


# Copy from the system to the working folder
if [ "$1" = "update" ]; then
	files=$(getfiles)
	for item in $files; do
		cp ~/."$item" ./"$item" 
	done
	exit
fi
